development: &default
  adapter: postgresql
  encoding: unicode
  database: twitter_api_search_development
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  <<: *default
  database: twitter_api_search_test

production:
  <<: *default
